using RoboChemist.Shared.DTOs.Common;
using static RoboChemist.Shared.DTOs.SlideDTOs.SlideRequestDTOs;
using static RoboChemist.Shared.DTOs.SlideDTOs.SlideResponseDTOs;

namespace RoboChemist.SlidesService.Service.Interfaces
{
    public interface ISlideService
    {
        /// <summary>
        /// Generate PowerPoint slides by authenticating user, processing payment, calling AI (Gemini) to generate JSON content,
        /// applying content to PowerPoint template, and uploading PPTX file to storage
        /// </summary>
        /// <param name="request">Slide generation request including AI prompt, number of slides, syllabus ID, and template ID</param>
        /// <returns>ApiResponse containing SlideDto with slide ID, file path, size, slide count, generation status, and processing time</returns>
        Task<ApiResponse<SlideDto>> GenerateSlideAsync(GenerateSlideRequest request);

        /// <summary>
        /// Get all slides generated by a specific user with pagination, filtering by grade/topic, and sorting options
        /// </summary>
        /// <param name="userId">User unique identifier</param>
        /// <param name="request">Request containing pagination (pageNumber, pageSize), filters (gradeId, topicId, status), and sort options (sortBy, sortOrder)</param>
        /// <returns>ApiResponse containing paginated list of SlideDetailDtos with full hierarchy (Grade → Topic → Syllabus → Slide)</returns>
        Task<ApiResponse<PaginatedResult<SlideDetailDto>>> GetSlidesAsync(GetSlidesRequest request);

        /// <summary>
        /// Download PowerPoint file by slide ID from storage
        /// </summary>
        /// <param name="slideId">Generated slide unique identifier</param>
        /// <returns>Tuple containing file stream, content type, and filename for download</returns>
        Task<(Stream FileStream, string ContentType, string FileName)> DownloadSlideAsync(Guid slideId);
    }
}
