using Microsoft.AspNetCore.Mvc;
using RoboChemist.Shared.DTOs.Common;
using RoboChemist.SlidesService.Service.Interfaces;
using static RoboChemist.Shared.DTOs.SlideDTOs.SlideRequestDTOs;
using static RoboChemist.Shared.DTOs.SlideDTOs.SlideResponseDTOs;
using static RoboChemist.Shared.DTOs.TopicDTOs.TopicDTOs;

namespace RoboChemist.SlidesService.API.Controllers
{
    [Route("api/v1/slides")]
    [ApiController]
    public class SlideController : ControllerBase
    {
        private readonly ISlideService _slideService;

        public SlideController(ISlideService slideService)
        {
            _slideService = slideService;
        }

        /// <summary>
        /// Generate PowerPoint slides automatically using AI (Gemini). Process flow: authenticate user → payment → AI generates JSON content → apply to PowerPoint template → upload file to storage
        /// </summary>
        /// <param name="request">Slide generation request containing AiPrompt, NumberOfSlides, SyllabusId, and TemplateId</param>
        /// <returns>ApiResponse with SlideDto containing GeneratedSlideId, FilePath, FileSize, SlideCount, GenerationStatus, ProcessingTime, and GeneratedAt</returns>
        [HttpPost("generate")]
        public async Task<ActionResult<ApiResponse<SlideDto>>> GenerateSlide([FromBody] GenerateSlideRequest request)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    var errors = ModelState.Values
                        .SelectMany(v => v.Errors)
                        .Select(e => e.ErrorMessage)
                        .ToList();

                    return BadRequest(ApiResponse<TopicDto>.ErrorResult("Dữ liệu xác thực không hợp lệ", errors));
                }

                var result = await _slideService.GenerateSlideAsync(request);

                return result.Success ? Ok(result) : BadRequest(result);
            }
            catch (Exception)
            {
                return StatusCode(500, ApiResponse<TopicDto>.ErrorResult("Lỗi hệ thống"));
            }
        }

        /// <summary>
        /// Get all slides generated by the current authenticated user (get all for admin account) with pagination, filters, and sorting.
        /// Supports filtering by grade, topic, and generation status. Supports sorting by generated date, grade name, topic order, and lesson order.
        /// </summary>
        /// <param name="pageNumber">Page number (default: 1)</param>
        /// <param name="pageSize">Number of items per page (default: 10, max: 100)</param>
        /// <param name="gradeId">Filter by grade ID (optional)</param>
        /// <param name="topicId">Filter by topic ID (optional)</param>
        /// <param name="generationStatus">Filter by generation status: Pending, Completed, Failed (optional)</param>
        /// <param name="sortBy">Sort field: GeneratedAt (default), GradeName, TopicSortOrder, LessonOrder</param>
        /// <param name="sortOrder">Sort direction: asc or desc (default: desc)</param>
        /// <returns>Paginated list of SlideDetailDto with full hierarchy information (Grade → Topic → Syllabus → Slide)</returns>
        [HttpGet]
        public async Task<ActionResult<ApiResponse<PaginatedResult<SlideDetailDto>>>> GetSlides(
            [FromQuery] int pageNumber = 1,
            [FromQuery] int pageSize = 10,
            [FromQuery] Guid? gradeId = null,
            [FromQuery] Guid? topicId = null,
            [FromQuery] string? generationStatus = null,
            [FromQuery] string sortBy = "GeneratedAt",
            [FromQuery] string sortOrder = "desc")
        {
            try
            {
                var request = new GetSlidesRequest
                {
                    PageNumber = pageNumber,
                    PageSize = pageSize,
                    GradeId = gradeId,
                    TopicId = topicId,
                    GenerationStatus = generationStatus,
                    SortBy = sortBy,
                    SortOrder = sortOrder
                };

                var result = await _slideService.GetSlidesAsync(request);

                return result.Success ? Ok(result) : BadRequest(result);
            }
            catch (Exception ex)
            {
                return StatusCode(500, ApiResponse<PaginatedResult<SlideDetailDto>>.ErrorResult("Lỗi hệ thống", [ex.Message]));
            }
        }

        /// <summary>
        /// Download PowerPoint file by slide ID. Returns file stream with proper content type and filename
        /// </summary>
        /// <param name="id">Generated slide ID</param>
        /// <returns>PPTX file stream for download</returns>
        [HttpGet("{id}/download")]
        public async Task<IActionResult> DownloadSlide(Guid id)
        {
            try
            {
                var (fileStream, contentType, fileName) = await _slideService.DownloadSlideAsync(id);

                return File(fileStream, contentType, fileName);
            }
            catch (InvalidOperationException ex)
            {
                return NotFound(ApiResponse<string>.ErrorResult(ex.Message));
            }
            catch (Exception ex)
            {
                return StatusCode(500, ApiResponse<string>.ErrorResult("Lỗi hệ thống khi tải file", [ex.Message]));
            }
        }
    }
}
